string  srcNodeType #源节点类型
string  srcNodeName #源节点名/源进程名
uint16  type        #写服务类型
string  args        #写内容参数,使用json格式
---
int32   result      #写服务状态，例如成功或失败
int32   errCode     #写服务错误码
string  content     #写服务返回值内容,使用json格式
